### ISSUE TITLE
java.lang.IllegalStateException: Reply already submitted

### ISSUE THREAD

**Issue by shinayser** [shadow-app/flutter_audio_recorder#13]
Hello!

If the user taps "deny" to both permissions, the app crashes:
```
Process: com.denox.mydenox.v2.dev, PID: 32224
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=200, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.denox.mydenox.v2.dev/com.denox.mydenox.v2.MainActivity}: java.lang.IllegalStateException: Reply already submitted
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4382)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4426)
        at android.app.ActivityThread.-wrap20(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1685)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6626)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
     Caused by: java.lang.IllegalStateException: Reply already submitted
        at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:148)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:234)
        at com.zeno.flutter_audio_recorder.FlutterAudioRecorderPlugin.onRequestPermissionsResult(FlutterAudioRecorderPlugin.java:79)
        at io.flutter.app.FlutterPluginRegistry.onRequestPermissionsResult(FlutterPluginRegistry.java:194)
        at io.flutter.app.FlutterActivityDelegate.onRequestPermissionsResult(FlutterActivityDelegate.java:126)
        at io.flutter.app.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:137)
        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7458)
        at android.app.Activity.dispatchActivityResult(Activity.java:7309)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4378)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4426) 
        at android.app.ActivityThread.-wrap20(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1685) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6626) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811) 
```

I use other apps that asks for permissions, like `permission_handler`, but I am not calling them in this context, just `flutter_audio_recorder`. 

Possibly this might be the problem?

**Comment by eric-5512** [comment]
Hello, my app will crash when it is authorized or rejected the first time it is loaded. Seeing that logcat has the same error as you, did you solve it?


>  Process: com.example.jx_mobile, PID: 28105
>     java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=200, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.example.jx_mobile/com.example.jx_mobile.MainActivity}: java.lang.IllegalStateException: Reply already submitted
>         at android.app.ActivityThread.deliverResults(ActivityThread.java:4461)
>         at android.app.ActivityThread.handleSendResult(ActivityThread.java:4503)
>         at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
>         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
>         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1839)
>         at android.os.Handler.dispatchMessage(Handler.java:106)
>         at android.os.Looper.loop(Looper.java:201)
>         at android.app.ActivityThread.main(ActivityThread.java:6864)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
>      Caused by: java.lang.IllegalStateException: Reply already submitted
>         at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:148)
>         at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:234)
>         at com.zeno.flutter_audio_recorder.FlutterAudioRecorderPlugin.onRequestPermissionsResult(FlutterAudioRecorderPlugin.java:79)
>         at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEnginePluginRegistry.java:612)
>         at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onRequestPermissionsResult(FlutterEnginePluginRegistry.java:356)
>         at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:509)
>         at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:611)
>         at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7757)
>         at android.app.Activity.dispatchActivityResult(Activity.java:7602)
