### ISSUE TITLE
Android - recorded WAV file cannot play with ExoPlayer

### ISSUE THREAD

**Issue by dfdgsdfg** [shadow-app/flutter_audio_recorder#46]
In Flutter, same error as below.

- https://github.com/ryanheise/just_audio (baked android exoplayer)
- https://github.com/florent37/Flutter-AssetsAudioPlayer  (baked android exoplayer)
- https://github.com/danielR2001/flutter_exoplayer (baked android exoplayer)

https://github.com/ryanheise/just_audio/issues/158

```
E/ExoPlayerImplInternal(12865): Source error
E/ExoPlayerImplInternal(12865):   com.google.android.exoplayer2.ParserException: Expected block size: 2; got: 1
E/ExoPlayerImplInternal(12865):       at com.google.android.exoplayer2.extractor.wav.WavExtractor$PassthroughOutputWriter.<init>(WavExtractor.java:222)
E/ExoPlayerImplInternal(12865):       at com.google.android.exoplayer2.extractor.wav.WavExtractor.read(WavExtractor.java:122)
E/ExoPlayerImplInternal(12865):       at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:982)
E/ExoPlayerImplInternal(12865):       at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
E/ExoPlayerImplInternal(12865):       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/ExoPlayerImplInternal(12865):       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/ExoPlayerImplInternal(12865):       at java.lang.Thread.run(Thread.java:764)
```

**Comment by dfdgsdfg** [comment]
#34 
#11 

In the #11, has some workaround.
