### ISSUE TITLE
CreateDataFile FAILED on IOS DEVICES

### ISSUE THREAD

**Issue by Larens94** [shadow-app/flutter_audio_recorder#60]
hello everyone, I am having a problem on several IOS devices that I have tried.
*** I specify that it works correctly in the emulator.

logs:
hasPermissions
granted
flutter: /var/mobile/Containers/Data/Application/4AC9DFA4-00B2-4D44-830F-A8201A623C5F/Documents1618350826992.wav
init
m: .wav /var/mobile/Containers/Data/Application/4AC9DFA4-00B2-4D44-830F-A8201A623C5F/Documents1618350826992.wav
 CreateDataFile failed
 Couldn't create a new audio file object
current
flutter: Instance of 'Recording'
flutter: RecordingStatus.Initialized

[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: FileSystemException: Cannot delete file, path = '/var/mobile/Containers/Data/Application/4AC9DFA4-00B2-4D44-830F-A8201A623C5F/Documents1618350826992.wav' (OS Error: No such file or directory, errno = 2)
#0      _File._delete.<anonymous closure> (dart:io/file_impl.dart:283:9)
#1      _rootRunUnary (dart:async/zone.dart:1362:47)
#2      _CustomZone.runUnary (dart:async/zone.dart:1265:19)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:152:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:704:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:733:32)
#6      Future._completeWithValue (dart:async/future_impl.dart:539:5)
#7      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:577:7)
#8      _rootRun (dart:async/zone.dart:1354:13)
#9      _CustomZone.run (dart:async/zone.dart:1258:19)
#10     _CustomZone.runGuarded (dart:async/zone.dart:1162:7)
#11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)

I await replies thank you very much.
with regard

**Comment by singh-karan-7** [comment]
I have the same issue. I ave tried other audio recording libraries too. All are giving this same error. Did you find the solution?
